<?php

require_once 'DataAccess.inc';
//use DataAccess;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Broker
 *
 * @author kami
 */
class BrokerPropertyType {

    public $BrokerPropertyTypeId = 1;
    public $Name;
    public $Comment;

}
